### ISSUE TITLE
Slider3D not returning any sound?

### ISSUE THREAD

**Issue by lRaulMN7** [SlicerIGT/SlicerSoundControl#4]
Hello. I'm testing your demo before I start doing some code.
I'm new into Slider3D and PureData.

I installed SlicerITG Extension and the SoundControl One.
I'm using w10 so I installed pd-l2ork-2.4.8 win-i686 from jonwwilkes's fork from the purr-data repository.
I also installed the pd-extended version that you recommend. When I launch the .pd file on his own, it provides sound. However, when I set the file into Slider3D and I start the server, I can't hear anything. The application is not producing any sound as I can't find the application in my volume master.

I guess I did something wrong while I was installing everything, do you know where I might have done something wrong? Thanks in advance.

**Comment by lRaulMN7** [comment]
Ok, I was missing the reference to the pd.exe file. My bad 👍 
As feedback, this could be added to the Install & Set-Up steps!

**Comment by lassoan** [comment]
Great, thanks for the update. I'm not exactly sure what detail is missing from the instructions. Would you mind suggesting a change by [editing the Readme file](https://github.com/SlicerIGT/SlicerSoundControl/edit/master/README.md)? You'll be offered to create a fork when you start editing and create a pull request when you are done. Thank you!
