### ISSUE TITLE
Issue starting puredata

### ISSUE THREAD

**Issue by smallvalthoss** [SlicerIGT/SlicerSoundControl#9]
I have the following installed using slicer 4.10.2:
-Puredata 0.51-3
-SlicerIGT
-SoundControl

When I run the OscSimpleTest.pd on BreachWarningScene.mrb I get the following error:
Traceback (most recent call last):
  File "C:/Users/Madhavi/AppData/Roaming/NA-MIC/Extensions-28257/SoundControl/lib/Slicer-4.10/qt-scripted-modules/OpenSoundControl.py", line 155, in startServer
    self.logic.startPureData(self.pureDataConfigFilePathSelector.currentPath, self.showPureDataGUI.checked)
  File "C:/Users/Madhavi/AppData/Roaming/NA-MIC/Extensions-28257/SoundControl/lib/Slicer-4.10/qt-scripted-modules/OpenSoundControl.py", line 253, in startPureData
    self.pureDataProcess = subprocess.Popen(args)
  File "C:\Program Files\Slicer 4.10.2\lib\Python\Lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "C:\Program Files\Slicer 4.10.2\lib\Python\Lib\subprocess.py", line 640, in _execute_child
    startupinfo)
WindowsError: [Error 87] The parameter is incorrect

Seems like it is having trouble opening the PureData GUI?? Idk.

**Comment by lassoan** [comment]
Use latest Plus version and latest Slicer Stable Release or latest Slicer Preview Release and let us know if you run into any problems.

**Comment by smallvalthoss** [comment]
> 
> 
> Use latest Plus version and latest Slicer Stable Release or latest Slicer Preview Release and let us know if you run into any problems.

Thanks for the reply

Using I Slicer 4.11.20210226, I get the following as error:
Traceback (most recent call last):
  File "C:/Users/Madhavi/AppData/Local/NA-MIC/Slicer 4.11.20210226/NA-MIC/Extensions-29738/SoundControl/lib/Slicer-4.11/qt-scripted-modules/OpenSoundControl.py", line 43, in __init__
    self.logic = OpenSoundControlLogic()
  File "C:/Users/Madhavi/AppData/Local/NA-MIC/Slicer 4.11.20210226/NA-MIC/Extensions-29738/SoundControl/lib/Slicer-4.11/qt-scripted-modules/OpenSoundControl.py", line 178, in __init__
    self.oscClient = OSC.OSCClient()
AttributeError: module 'OSC' has no attribute 'OSCClient'

I checked https://github.com/SlicerIGT/SlicerSoundControl/issues/8 and tried changing the __init__ file to do the from OSC import *. However, it was already there. Not sure how to fix it.

**Comment by lassoan** [comment]
Thanks for testing. I've updated the extension for Python3, it should work from tomorrow, just update to latest Slicer Preview Release and install the extension; or in latest Slicer Stable Release update SoundControl extension.

**Comment by smallvalthoss** [comment]
> 
> 
> Thanks for testing. I've updated the extension for Python3, it should work from tomorrow, just update to latest Slicer Preview Release and install the extension; or in latest Slicer Stable Release update SoundControl extension.

I downloaded the newest preview release, but it looks like the extension is missing. It says something like "not found for current slicer version (was last used in Slicer version 29738)". I also couldn't find anywhere to update the extension on slicer 4.11.2021226. Is it something I can just download and cmake from this github? I am a little unsure of how to do that though.

**Comment by lassoan** [comment]
There was a packaging error that prevented creating the updated release. I've fixed it now and so the package should be available tomorrow.

If you don't want to wait another day then just replace the OpenSoundControl module folder content with the current content of the OpenSoundControl folder in this git repository. Delete the old OSC subfolder (OSC interface is not obtained by using pip install).

**Comment by smallvalthoss** [comment]
> Is it something I can just download and cmake from this github? I am a little unsure of how to do that though.

I have a version of slicer made from source if that helps, but not really sure how to make for that

**Comment by smallvalthoss** [comment]
> 
> 
> There was a packaging error that prevented creating the updated release. I've fixed it now and so the package should be available tomorrow.
> 
> If you don't want to wait another day then just replace the OpenSoundControl module folder content with the current content of the OpenSoundControl folder in this git repository. Delete the old OSC subfolder (OSC interface is not obtained by using pip install).

Thank you, I will try it after my exam :)
